apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
    - port: 80 # service
      targetPort: 80 # container
      nodePort: 30080 # external (node)